# SPDX-FileCopyrightText: 2023 Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

# Builds the flutter frontend
# Doesn't run tests yet though

name: Flutter-dev

on:
  push:
    branches:
      - 2.1
      - main
  pull_request:
    branches:
      - 2.1
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        preset:
          - name: dev-flutter
            isAOT: false
            args: []
          - name: dev-flutter-asan
            isAOT: false
            args: ["--asan"]
          - name: dev-flutter-aot
            isAOT: true
            args: ["--aot"]
          - name: dev-flutter-aot-asan
            isAOT: true
            args: ["--aot", "--asan"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt update -qq
          sudo apt install libgtk-3-dev libglib2.0-dev ninja-build libspdlog-dev lld xvfb -y

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      # Chose engine from https://github.com/ardera/flutter-ci/releases
      - name: Download flutter engine
        run: |
          wget --no-verbose https://github.com/ardera/flutter-ci/releases/download/engine%2F55eae6864b296dd9f43b2cc7577ec256e5c32a8d/x64-generic.tar.xz
          mkdir flutter_engine
          tar xvf x64-generic.tar.xz -C flutter_engine
          cd flutter_engine
          mkdir dbg rel
          cp libflutter_engine.so.debug dbg/libflutter_engine.so
          cp libflutter_engine.so.release rel/libflutter_engine.so

      - name: Configure project ${{ matrix.preset.name }}
        run: cmake -S . -B ./build-${{ matrix.preset.name }} --preset ${{ matrix.preset.name }}
        env:
          FLUTTER_ENGINE_FOLDER: "${{ github.workspace }}/flutter_engine/"

      - name: Build Project ${{ matrix.preset.name }}
        run: cmake --build ./build-${{ matrix.preset.name }}

      - name: Build test embedder .dart
        if: ${{ matrix.preset.isAOT == false }}
        run: |
          cd tests/flutter_tests_embedder/
          flutter build bundle --suppress-analytics

      - name: Build test embedder .dart (AOT)
        if: ${{ matrix.preset.isAOT }}
        run: |
          cd tests/flutter_tests_embedder/
          flutter build linux --release --suppress-analytics

      - name: Build the example
        run: |
          cd examples/flutter
          flutter build linux

      - name: Run tests
        run: xvfb-run dart run_flutter_tests.dart ${{ join(matrix.preset.args, ' ') }}
